# Site wide configuration

title:  Ben.Codes
locale: en_US
url:


# Jekyll configuration

permalink:   /:year-:month-:day/:title
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Ben Collins
  avatar: headshot-greyscale.jpg
  bio: "Christian, programmer, husband & daddy, wannabe triathlete"
  email: aggieben@gmail.com
  disqus-shortname: bencodes
  twitter: aggieben
  facebook: #username
  google:
    plus:
    analytics: UA-75176-10
    verify: ATAv-6F9Inq1N0mCqEuE61wRR-Bv1U2LzuslYW-_xjA
    ad-client:
    ad-slot:
  bing-verify:
  github: aggieben
  stackoverflow: 3279/ben-collins
  linkedin: bcollins
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
