name: Ben codes
description: Christian, programmer, husband & daddy, wannabe triathlete.
meta_description: "Ben Collins, blogging mostly about programming"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'ben.codes'
google_analytics: 'UA-75176-10'
disqus: true
disqus_shortname: 'bencodes'

# Details for the RSS feed generator
url:            'ben.codes'
author:         'Ben Collins'
authorTwitter:  'aggieben'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
